apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: Yml1c2Vy # biuser
  password: YmlwYXNzd29yZA== # bipassword
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  username: Yml1c2Vy # biuser
  password: YmlwYXNzd29yZA== # bipassword
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRES_USER: Yml1c2Vy # biuser
  POSTGRES_PASSWORD: YmlwYXNzd29yZA== # bipassword
  MONGO_USER: Yml1c2Vy
  MONGO_PASSWORD: YmlwYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_SECRET: YmktY291cnNlLXNlY3JldC1rZXk= # bi-course-secret-key
