apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-ui
  template:
    metadata:
      labels:
        app: course-ui
    spec:
      containers:
        - name: course-ui
          image: bi-course-react:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: course-ui
spec:
  selector:
    app: course-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
